### ISSUE TITLE
`flutter` post-install script failure

### ISSUE THREAD

**Issue by ZzZombo** [lukesampson/scoop-extras#5922]
```
Installing 'flutter' (2.0.3) [64bit] [extras]
WARN  By installing you accept following license: BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause.html)
Loading flutter_windows_2.0.3-stable.zip from cache.
Loading flutter-dev-setup.ps1 from cache.
Checking hash of flutter_windows_2.0.3-stable.zip ... ok.
Checking hash of flutter-dev-setup.ps1 ... ok.
Extracting flutter_windows_2.0.3-stable.zip ... done.
Linking I:\apps\windows\scoop\apps\flutter\current => I:\apps\windows\scoop\apps\flutter\2.0.3
Creating shim for 'flutter'.
Creating shim for 'flutter-dev-setup'.
Running post-install script...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more
ERROR You cannot call a method on a null-valued expression.
```
I don't know what does this mean and what to do. Anybody else?

**Comment by MunsterPlop** [comment]
This might mean you're not using the right java version.
You might want to try https://github.com/lukesampson/scoop/wiki/Java#switching-javas and see which one works.
If I remember, for Android Sdk related installations, Java 8 works but anything above doesn't.

**Comment by Findulas** [comment]
Yes, the java version is problem. It would be preferable, when the post install script first tries to get the "scooped" correct java version. The one on the path might be the wrong one.
In my environment I  use jdk11 as standard, global installed and jdk8 local installed for development. Thist means jdk11 is the first in the path.
